package netSecMon;

public enum Status {
	LOADING, RUNNING, SUSPENDED, WAITING, CONNECTED, 
	IN_QUEUE, IN_WAITQUEUE, RESOURCE_UNAVAILABLE, 
	AWAITING_RESOURCE, IOEXCEPTION, SOCKETEXCEPTION,
	CONNECTEXCEPTION, SSLHANDSHAKEEXCEPTION, SSLPEERUNVERIFIEDEXCEPTION,
	IOEXCEPTION_GET, CERTIFICATEEXCEPTION, VALIDATOREXCEPTION
}
